const commando = require ('discord.js-commando')

module.exports = class bertiebotts extends commando.Command {
	constructor(client) {
		super(client, {
			name: 'bertiebotts',
			group: 'spells',
			memberName: 'bertiebotts',
			description: 'BertieBotts every flavoured beans',
			throttling: {
				usages: 1,
				duration: 10,
			},
		});
	}
async run(message, args) {
 var bertiebottsRoll = Math.floor(Math.random() * 100) + 1;
    if(bertiebottsRoll > 51) {
 var bertiebottsGoodFlavours = [
        'Milk Chocolate🍫',
        'White-Chocolate🍫',
        'Marshmellow',
        'Milkshake🥛',
        'Caramilk',
        'Caramel',
        'Hazelnut',
        'Christmas Mint',
        'White Raspberry',
        'Spiced Pumpkin',
        'Latte☕',
        'Cappuccino☕',
        'Champagne🍷',
        'Dark Rum',
        'Raspberry',
        'French Toast🍞',
        'Sundae🍨',
        'Cheesecake🍰',
        'Strawberry Cheesecake🍰',
        'Short Bread🍞',
        'Lasagne',
        'Mint',
        'Butter Scotch',
        'Apple🍎',
        'Lime',
        'Banana🍌',
        'Coffee☕',
        'Butterbeer🍺',
        'Almond',
        'Blackberry',
        'Peppermint',
        'Baked Beans',
        'Éclair',
        'Fried Egg🥚',
        'Lobster🦞',
        'Lemon🍋',
        'Apple Pie',
        'Bacon 🥓',
        'Toast',
        'Pear🍐',
        'Tomato🍅',
        'Tutti-frutti',
        'Vanilla',
        'Vanilla Ice-Cream🍦',
        'Marmalade',
        'Coconut🥥',
        'Pink Grapefruit',
        'Steak🥩',
        'Strawberry🍓',
        'Peanut-Butter Ice-Cream🍦',
        'Chocolate Ice-Cream🍦',
        'Strawberry Ice-Cream',
        'Cheese🧀',
        'Cherry🍒',
        'Chilli',
        'Toffee',
        'Toffee Apple',
        'Toffee pudding',
        'Roast Beef',
        'Peach🍑',
        'Honey🍯',
        'Sausage',
        'Pizza🍕',
        'Orange',
        'Milk🥛',
        'Youth',
        'Carrot Cake🍰',
        'Cake 🍰 ',
        'Snow Cone',
        'Lemonade',
        'Coca-Cola',
        'Toffee Cake🍰',
        'Popcorn',
        'Creaming Soda',
        'Pineapple',
        'Grape',
    ]
    var bbgf = Math.floor(Math.random() * bertiebottsGoodFlavours.length);
     message.reply(`<:bertiebotts:726812982486761502> *Ate* a ***nice***  **${bertiebottsGoodFlavours[bbgf]}** Flavoured bean. 😄`)
    }
     else if(bertiebottsRoll <= 50){
    var bertiebottsBadFlavours = [
        'Pure Toothpaste',
        'Dog Food',
        'Dog Poo💩',
        'Poop💩',
        'Dirt',
        'Old Socks🧦',
        'Mandrake',
        'Unicorn Dung🦄💩',
        'Dung',
        'Toejam 🦶💦',
        'Soap',
        'Mushroom',
        'Dirty Sock🧦',
        'Sweaty Sock🧦',
        'Broccoli',
        'Raw Chilli Powder',
        'Cold-Gravy',
        'Sulphur',
        'Rotten Egg',
        'Rotten Milk',
        'Rotten Apple',
        'Septic Tank',
        'Pepper',
        'Grease',
        'Oil',
        'Mercury',
        'Pure Dark-Chocolate',
        '🦶 Feet',
        'Earwax',
        'Curry',
        'Rotten Meat',
        'Farm dirt',
        'Phlegm',
        'Horseraddish',
        'Wart',
        'Hair',
        'Wood',
        'Hoof',
        'Glass',
        'Goblin Wart',
        'Toenail',
        'Sweat',
        'FEAR ITSELF',
        "Voldemort's Patented Missing Nose",
        'Mulch',
        'Grass',
        'Boogie',
        'Corpse',
        'Death',
        'Hydrogen',
        'Dust',
        'Gunpowder',
        'Ink',
        'Rubber',
        "Belle Delphine's Bath Water",
        'Grey Water',
        'Spell Discharge',
        'Smoked Garbage',
        'Overcooked Cabbage',
        'Metal',
        'Dirty Nickel Coin',
        'Worm Slime',
        "Draco's Patented Hair Gel",
        'Polyjuice Essence',
        'Boil Juice',
        'Pumkin Soup',
        'Skele-Gro',
        'Troll Boogie',
        'Rotten Pumpkin',
        'Compost',
        "Panda's anus",
        "Bumb crumb's",

    ]
    var bbbf = Math.floor(Math.random() * bertiebottsBadFlavours.length);
    message.reply(`<:bertiebotts:726812982486761502> *Ate* a ***putrid***  **${bertiebottsBadFlavours[bbbf]}** Flavoured bean. 🤮`)

     }







}
}